### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by limelect** [olegchensky/A-Tools#2]
Line 242 uProcesses
function ProcessRefresh(Modules: Boolean = False): Boolean; <<< 1 parameter

Line 318 UProc
 if ProcessRefresh(False, True) then begin <<< 2 parameters

On Uthread  Line 159 
undeclared icsDoOptimizeMemory although 
G:\Delphi Projects\olegchensky\icsv858 in path

That about it could not compile

**Comment by olegchensky** [comment]
Common --> uProcesses.pas --> 47:
function ProcessRefresh(const Modules: Boolean; const SetPrivileges: Boolean): Boolean;

**Comment by limelect** [comment]
Sorry but something is wrong
Line 47 you have Uproc on the main directory
IDE brought me there.
Sorry, it is your mess.
